title: App Showcase
description: Ever wondered who is building amazing apps using PhoneGap?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://phonegap.com" # the base hostname & protocol for your site

gems:
  - jekyll-paginate
  - jekyll-coffeescript

paginate: 10
paginate_list_count: 7
paginate_path: "/blog/page:num/"

post:
  template: _post.txt
  extension: md

markdown: kramdown

kramdown:
  input: GFM
